### ISSUE TITLE
Reference to LGPL found

### ISSUE THREAD

**Issue by rahulmohang** [jdeparser/jdeparser2#38]
Hi, 

There is a reference of LGPL v2.1 or later in the file, https://github.com/jdeparser/jdeparser2/blob/2.0.3.Final/pom.xml. Is the file licensed under LGPL v2.1 or later?

**Comment by dmlloyd** [comment]
No, it's just an oversight. There is no need for the POM to have any copyright notice or license information at all.

**Comment by rahulmohang** [comment]
OK. Thank you for the answer.
